kind: pipeline
type: docker
name: default

pipeline:
  beanstalk:
    image: pelotech/drone-elastic-beanstalk
    access_key:
      from_secret: access_key
    secret_key:
      from_secret: secret_key
    region: ap-southeast-2
    application: drone-ci-tester
    version_label: v1
    auto_create: true
    description: Deployed with DroneCI
    bucket_name: drone-test-1
    bucket_key:
      from_secret: bucket_key
      
