kind: pipeline
type: docker
name: default

pipeline:
  beanstalk:
    image: pelotech/drone-elastic-beanstalk
    access_key:
      from_secret: aws_access_key
    secret_key:
      from_secret: aws_secret_key
    region: ap-southeast-1
    application: drone-test
    version_label: v1
    description: Deployed with DroneCI
    bucket: drone-test-1
    bucket-key:
      from_secret: aws_access_key_id
    update_environment: true
    environment_name: DroneTest-env
